name: Check Repository Structure

on: [push, workflow_dispatch]

jobs:
  check-files:
    runs-on: macos-14
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: List All Files
      run: find . -maxdepth 3 -name "*.xcodeproj"
